# Noxwave UI package
[package]
name = "noxwave-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

# Dependencies
[dependencies]
gpui = {
    git = "https://github.com/zed-industries/zed",
    tag = "v1.13.2"
}

gpui_platform = {
    git = "https://github.com/zed-industries/zed",
    features = ["font-kit"],
    tag = "v1.13.2"
}
